version: '3.8'

services:
  asm3_postgres:
    build:
      context: ./postgres
    container_name: asm3_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asm"]
      interval: 10s
      timeout: 5s
      retries: 5

  asm3:
    build:
      context: ./asm3
    container_name: asm3
    depends_on:
      asm3_postgres:
        condition: service_healthy
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
